server:
  port: 8080

spring:
  application:
    name: casa-do-codigo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/casa_do_codigo_db?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: 2284789028